version: "3"
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d
      - ./data/nginx/html:/usr/share/nginx/html
      - ./data/logs/nginx:/var/log/nginx
    deploy:
      restart_policy:
        condition: on-failure
