"""add exception string

Revision ID: 26e5bb41b2ac
Revises: f2361e327f91
Create Date: 2021-04-17 04:00:53.938005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e5bb41b2ac'
down_revision = 'f2361e327f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jiandan', sa.Column('exception_string', sa.Text(), nullable=True))
    op.add_column('lvv2_image', sa.Column('exception_string', sa.Text(), nullable=True))
    op.add_column('lvv2_thread', sa.Column('exception_string', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lvv2_thread', 'exception_string')
    op.drop_column('lvv2_image', 'exception_string')
    op.drop_column('jiandan', 'exception_string')
    # ### end Alembic commands ###
