dsn: "root:@(127.0.0.1)/sys"

models:
  - name: jiandan_ooxx
    title: 图片
    attributes:
      - name: id
        display: ID
        tag: input
      - name: url
        display: 地址
        tag: input
      - name: status
        display: 状态
        tag: input
      - name: date
        display: 日期
        tag: input

    table:
      columns:
        - name: id
        - name: url
        - name: status
        - name: date
      actions:
        - name: create
          display: 创建
          type: dialog
          dialog:
            title: 创建实例
            fields:
              - name: id
              - name: url
              - name: status
              - name: date
      row_actions:
        - name: edit
          display: 编辑
          type: dialog
          dialog:
            title: 创建实例
            fields:
              - name: url
              - name: status
              - name: date
        - name: delete
          display: 删除
          type: message
        - name: view
          display: 查看

  - name: site
    title: 网站
    attributes:
      - name: id
        display: ID
        tag: input
      - name: name
        display: 名字
        tag: input
      - name: url
        display: URL
        tag: input

    table:
      columns:
        - name: id
        - name: name
        - name: url
      actions:
        - name: create
          display: 创建
